version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: consultorio_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: consultorio
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - consultorio_net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: consultorio_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - consultorio_net

volumes:
  db_data:

networks:
  consultorio_net:
    driver: bridge

